/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as EmissoesRouteImport } from './routes/emissoes'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as IntegracaoOktonRouteImport } from './routes/integracao-okton'
import { Route as IntegracaoWhatsappRouteImport } from './routes/integracao-whatsapp'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as RascunhosRouteImport } from './routes/rascunhos'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as TestesApiRouteImport } from './routes/testes-api'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as ApiPublicWhatsappTokenRouteImport } from './routes/api/public/whatsapp/$token'
import { Route as ApiPublicWebhooksOktonFiscalRouteImport } from './routes/api/public/webhooks/okton/fiscal'
import { Route as ApiPublicWebhooksWhatsappProviderRouteImport } from './routes/api/public/webhooks/whatsapp/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissoesRoute = EmissoesRouteImport.update({
  id: '/emissoes',
  path: '/emissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoOktonRoute = IntegracaoOktonRouteImport.update({
  id: '/integracao-okton',
  path: '/integracao-okton',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoWhatsappRoute = IntegracaoWhatsappRouteImport.update({
  id: '/integracao-whatsapp',
  path: '/integracao-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RascunhosRoute = RascunhosRouteImport.update({
  id: '/rascunhos',
  path: '/rascunhos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesApiRoute = TestesApiRouteImport.update({
  id: '/testes-api',
  path: '/testes-api',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappTokenRoute = ApiPublicWhatsappTokenRouteImport.update({
  id: '/api/public/whatsapp/$token',
  path: '/api/public/whatsapp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksOktonFiscalRoute =
  ApiPublicWebhooksOktonFiscalRouteImport.update({
    id: '/api/public/webhooks/okton/fiscal',
    path: '/api/public/webhooks/okton/fiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWhatsappProviderRoute =
  ApiPublicWebhooksWhatsappProviderRouteImport.update({
    id: '/api/public/webhooks/whatsapp/$provider',
    path: '/api/public/webhooks/whatsapp/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/emissoes': typeof EmissoesRoute
  '/empresas': typeof EmpresasRoute
  '/fluxos': typeof FluxosRoute
  '/integracao-okton': typeof IntegracaoOktonRoute
  '/integracao-whatsapp': typeof IntegracaoWhatsappRoute
  '/logs': typeof LogsRoute
  '/rascunhos': typeof RascunhosRoute
  '/simulador': typeof SimuladorRoute
  '/testes-api': typeof TestesApiRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/api/public/whatsapp/$token': typeof ApiPublicWhatsappTokenRoute
  '/api/public/webhooks/okton/fiscal': typeof ApiPublicWebhooksOktonFiscalRoute
  '/api/public/webhooks/whatsapp/$provider': typeof ApiPublicWebhooksWhatsappProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/emissoes': typeof EmissoesRoute
  '/empresas': typeof EmpresasRoute
  '/fluxos': typeof FluxosRoute
  '/integracao-okton': typeof IntegracaoOktonRoute
  '/integracao-whatsapp': typeof IntegracaoWhatsappRoute
  '/logs': typeof LogsRoute
  '/rascunhos': typeof RascunhosRoute
  '/simulador': typeof SimuladorRoute
  '/testes-api': typeof TestesApiRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/api/public/whatsapp/$token': typeof ApiPublicWhatsappTokenRoute
  '/api/public/webhooks/okton/fiscal': typeof ApiPublicWebhooksOktonFiscalRoute
  '/api/public/webhooks/whatsapp/$provider': typeof ApiPublicWebhooksWhatsappProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/emissoes': typeof EmissoesRoute
  '/empresas': typeof EmpresasRoute
  '/fluxos': typeof FluxosRoute
  '/integracao-okton': typeof IntegracaoOktonRoute
  '/integracao-whatsapp': typeof IntegracaoWhatsappRoute
  '/logs': typeof LogsRoute
  '/rascunhos': typeof RascunhosRoute
  '/simulador': typeof SimuladorRoute
  '/testes-api': typeof TestesApiRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/api/public/whatsapp/$token': typeof ApiPublicWhatsappTokenRoute
  '/api/public/webhooks/okton/fiscal': typeof ApiPublicWebhooksOktonFiscalRoute
  '/api/public/webhooks/whatsapp/$provider': typeof ApiPublicWebhooksWhatsappProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conversas'
    | '/emissoes'
    | '/empresas'
    | '/fluxos'
    | '/integracao-okton'
    | '/integracao-whatsapp'
    | '/logs'
    | '/rascunhos'
    | '/simulador'
    | '/testes-api'
    | '/usuarios'
    | '/webhooks'
    | '/api/public/whatsapp/$token'
    | '/api/public/webhooks/okton/fiscal'
    | '/api/public/webhooks/whatsapp/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conversas'
    | '/emissoes'
    | '/empresas'
    | '/fluxos'
    | '/integracao-okton'
    | '/integracao-whatsapp'
    | '/logs'
    | '/rascunhos'
    | '/simulador'
    | '/testes-api'
    | '/usuarios'
    | '/webhooks'
    | '/api/public/whatsapp/$token'
    | '/api/public/webhooks/okton/fiscal'
    | '/api/public/webhooks/whatsapp/$provider'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conversas'
    | '/emissoes'
    | '/empresas'
    | '/fluxos'
    | '/integracao-okton'
    | '/integracao-whatsapp'
    | '/logs'
    | '/rascunhos'
    | '/simulador'
    | '/testes-api'
    | '/usuarios'
    | '/webhooks'
    | '/api/public/whatsapp/$token'
    | '/api/public/webhooks/okton/fiscal'
    | '/api/public/webhooks/whatsapp/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConversasRoute: typeof ConversasRoute
  EmissoesRoute: typeof EmissoesRoute
  EmpresasRoute: typeof EmpresasRoute
  FluxosRoute: typeof FluxosRoute
  IntegracaoOktonRoute: typeof IntegracaoOktonRoute
  IntegracaoWhatsappRoute: typeof IntegracaoWhatsappRoute
  LogsRoute: typeof LogsRoute
  RascunhosRoute: typeof RascunhosRoute
  SimuladorRoute: typeof SimuladorRoute
  TestesApiRoute: typeof TestesApiRoute
  UsuariosRoute: typeof UsuariosRoute
  WebhooksRoute: typeof WebhooksRoute
  ApiPublicWhatsappTokenRoute: typeof ApiPublicWhatsappTokenRoute
  ApiPublicWebhooksOktonFiscalRoute: typeof ApiPublicWebhooksOktonFiscalRoute
  ApiPublicWebhooksWhatsappProviderRoute: typeof ApiPublicWebhooksWhatsappProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissoes': {
      id: '/emissoes'
      path: '/emissoes'
      fullPath: '/emissoes'
      preLoaderRoute: typeof EmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao-okton': {
      id: '/integracao-okton'
      path: '/integracao-okton'
      fullPath: '/integracao-okton'
      preLoaderRoute: typeof IntegracaoOktonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao-whatsapp': {
      id: '/integracao-whatsapp'
      path: '/integracao-whatsapp'
      fullPath: '/integracao-whatsapp'
      preLoaderRoute: typeof IntegracaoWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rascunhos': {
      id: '/rascunhos'
      path: '/rascunhos'
      fullPath: '/rascunhos'
      preLoaderRoute: typeof RascunhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes-api': {
      id: '/testes-api'
      path: '/testes-api'
      fullPath: '/testes-api'
      preLoaderRoute: typeof TestesApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/$token': {
      id: '/api/public/whatsapp/$token'
      path: '/api/public/whatsapp/$token'
      fullPath: '/api/public/whatsapp/$token'
      preLoaderRoute: typeof ApiPublicWhatsappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/okton/fiscal': {
      id: '/api/public/webhooks/okton/fiscal'
      path: '/api/public/webhooks/okton/fiscal'
      fullPath: '/api/public/webhooks/okton/fiscal'
      preLoaderRoute: typeof ApiPublicWebhooksOktonFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp/$provider': {
      id: '/api/public/webhooks/whatsapp/$provider'
      path: '/api/public/webhooks/whatsapp/$provider'
      fullPath: '/api/public/webhooks/whatsapp/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConversasRoute: ConversasRoute,
  EmissoesRoute: EmissoesRoute,
  EmpresasRoute: EmpresasRoute,
  FluxosRoute: FluxosRoute,
  IntegracaoOktonRoute: IntegracaoOktonRoute,
  IntegracaoWhatsappRoute: IntegracaoWhatsappRoute,
  LogsRoute: LogsRoute,
  RascunhosRoute: RascunhosRoute,
  SimuladorRoute: SimuladorRoute,
  TestesApiRoute: TestesApiRoute,
  UsuariosRoute: UsuariosRoute,
  WebhooksRoute: WebhooksRoute,
  ApiPublicWhatsappTokenRoute: ApiPublicWhatsappTokenRoute,
  ApiPublicWebhooksOktonFiscalRoute: ApiPublicWebhooksOktonFiscalRoute,
  ApiPublicWebhooksWhatsappProviderRoute:
    ApiPublicWebhooksWhatsappProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
